server:
  port: 8081
spring:
  ai:
    openai:
      base-url: http://127.0.0.1:8081/
      api-key: xxx
      chat:
        options:
          model: GLM-5.3
        embedding-model: text-embedding-ada-002
        embedding:
          options:
            num-batch: 1536
    agent:
      base-url: https://open.bigmodel.cn/api/coding/paas/v4/
      api-key: xxx


logging:
  level:
    root: info

